# Generated by Django 4.1.2 on 2022-10-07 08:06

from django.db import migrations

def create_data(apps, schema_editor):
    Teacher = apps.get_model('teachers', 'Teacher')
    Teacher(name="Joe Silver", email="joe@email.com", document="22342342", phone="00000000").save()

class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]